# -*- coding: utf-8 -*-
"""Streamlit.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1on4HMoVtgLtKKytXd3Tk8HzQOYAF3GUY
"""

import streamlit as st

st.write("""
Maximum of three numbers
""")

st.header('User Input Parameters')
st.subheader('User Input parameters')
n1 = st.number_input("Number_1")
n2 = st.number_input("Number_2")
n3 = st.number_input("Number_3")
#st.write(n1)
#st.write(n2)
#st.write(n3)


st.subheader('Largest of above three numbers is')
st.write(str(max(n1,n2,n3)))
